### ISSUE TITLE
Multiple comparisons corrections for temporal decoding results

### ISSUE THREAD

**Issue by Feugs** [DDTBOX/DDTBOX#62]
Currently multiple comparisons corrections are not being applied correctly to correct for multiple channels of temporal decoding results. This is because each temporal decoding result is stored as an analysis (na), rather than a time window (step), and existing multiple comparisons correction methods work across steps to count the number of analyses. 

We need to make special cases for correction of temporal decoding results, counting tests over the analysis (na) dimension rather than across time windows/steps.

**Comment by Feugs** [comment]
Fixed, temporal decoding results are now corrected for multiple comparisons across channels (within the same analysis time window)

**Comment by palday** [comment]
What do the cluster analysis (Maris, etc.) guys do for this type of stuff? The methods we're using here are essentially cluster procedures with the dependent and independent variables in some sense "reversed" -- we're predicting conditions from EEG, instead of EEG from conditions (which is what traditional ANOVA, the usual application of mixed models, or even mass-univariate procedures do).

**Comment by Feugs** [comment]
Cluster-based multiple comparisons corrections across channels (for temporal decoding accuracy scores at the group level, or FW Z-scores) requires a channel neighbourhood matrix, which is basically a matrix of 1s and 0s denoting which channels are adjacent to which other channels. Statistically significant results (according to some arbitrary threshold, usually p < 0.05 or 0.01) at adjacent channels are used to form clusters in the actual results and permutation samples. 

This is pretty easy to implement (I've made a version of this for a previous project), but requires some work by the user to determine which channels should count as adjacent (i.e. spatial neighbours). Adjacent electrodes can be created using a simple distance rule (e.g. adjacent if less than X cm away in 3D space), as implemented for example in the LIMO EEG toolbox. 

We could extend this to spatiotemporal clustering (across adjacent electrodes and time points) as well, although most of the applications of DDTBOX so far haven't really required temporal decoding or FWs analyses on multiple time windows.

**Comment by palday** [comment]
Call it an *adjacency matrix* please so that it matches up with the standard terminology in graph theory.

Another option for 10/20 and 10/10 systems is to check lateral proximity by the number portion of electrode name and sagital proximity by letter and add a threshold for number of 'skipped' positions -- i.e. Pz and Cz are not typically adjacent but in a low enough density setup without CPz, they might be.
