### ISSUE TITLE
example dataset for decoding tutorial (DDTBOX)

### ISSUE THREAD

**Issue by xc128** [DDTBOX/DDTBOX#76]
I didn’t get the same plot for subject No.2 as was shown in the decoding tutorial though I run decoding analyses using the example dataset (download here). Then I compared the decoding result of subject No.2 (from the example dataset for the group-level tutorial) with mine. I found that the settings of sbj_code (i.e. 'DATA/Tutorial Dataset/Reduced/1_sp') and nsbj (i.e. 40) are different from the settings of sbj_code (i.e. ['EEG data/sbj1'];... % subject 1) and nsbj (i.e. 5) as suggested by the decoding tutorial. I don't know why the settings of the sbj_code and nsbj are something like these. Also, I wonder if it is right to feed the example dataset (download here) into the SVM classifier. I guess we don’t feed the same dataset into the SVM classifier and that is why we get different plots. Attached please find my plot. Please check my decoding results of subject No.2 in the Dropbox (https://www.dropbox.com/s/xd3f3gi6xwm8jfv/FLANKER_SBJ2_win10_steps10_av1_st3_SVM_LIBSVM_DCGCorrect%20vs.%20Error.mat?dl=0). Thank you very much for your kind attention!
![sbj2_step10_20171102](https://user-images.githubusercontent.com/33345235/32367617-aa6d32a8-c0bd-11e7-94fd-4cd2aa45b9a2.jpg)

**Comment by Feugs** [comment]
Hi xc128,

Thank you for providing a description of this issue with your example results figure, and thanks for using our toolbox! We have a dedicated mailing list for technical support, and we use the Github Issue Tracker only for bug reports and feature requests. Please subscribe to the [DDTBOX mailing list](https://www.freelists.org/list/ddtbox) and post your question there, so that the community of DDTBOX users can offer advice and also benefit from discussion of the issue. If you post on the mailing list then I will be happy to offer a reply and help you however I can.

Kind regards,

Daniel
