### ISSUE TITLE
About default options of dd_convert_eeg_data()

### ISSUE THREAD

**Issue by neurothew** [DDTBOX/DDTBOX#80]
In dd_convert_eeg_data(), it seems that for the default options {timepoints: 'all'}, the epoch_start_idx and epoch_end_idx are not defined. They are only defined when user specify the timepoints themselves.

**Comment by Feugs** [comment]
Hi Matthew,

Thank you for finding and reporting this bug. To clarify, the above comment refers to variables `epoch_start_index` and `epoch_end_index` within the function. When these are not specified the function `dd_convert_eeg_data` crashes when the time range within the epoch is not specified.

If you have already implemented a bugfix for this, please let us know and we may be able to integrate it into an updated version of DDTBOX. Otherwise I will get onto fixing this.
